[package]
name = "autoplank"
version = "0.1.0"
authors = ["Edwin Svensson <git@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
